### PR TITLE
allow users to specify completion suggestion priority

### PR DESCRIPTION
**Pull request by aviatesk**

### CODE REVIEW

**Comment by aviatesk** [comment]
@ashthespy any update on this ? The default behavior is same as before, but this just gives us more customizability.

**Comment by ashthespy** [comment]
@aviatesk Sorry, this slipped under the radar. 
Its been a while since I played with autocomplete, but from what I understand, this would let users set it to `1`, overriding user snippets (`snippets.cson`)? 

PS: `s/privided/provided/`

**Comment by aviatesk** [comment]
If an user set `completion_suggestion_priority` to `1`, then the priority of snippet completion and that of atom-latex's completions are equivalent, which would result in snippet completions appear first by some mechanism inside autocomplete-plus.

If an user doesn't tweak this setting, then the completions from this package appear first than snippets as before.

An user can even give higher priority to this in order to make the completions from this package superior to completions from any provider.

**Comment by aviatesk** [comment]
@ashthespy bump :p Do you have any objection for this ?

**Comment by ashthespy** [comment]
Added in `v0.9.1` thanks!

**Pull request closed without merging**
